const data = [
    {
        _creator: '619ac04f96bfc93671b2be9f',
        name: 'Bonnes Mares',
        description: 'Deep and elegantly muscular, the 2019 Bonnes-Mares Grand Cru (Domaine Louis Jadot) is a layered, fleshy but tightly wound wine evocative or orange rind, rose petals, sweet berry fruit and raw cocoa. Full-bodied and concentrated, with a long, mineral finish, it will reward bottle age.',
        type: 'red',
        brand: 'Jadot',
        grape: ['pinot noir'],
        country: 'france',
        region: 'burgundy',
        year: 2019,
        volume: 0.750,
        basePrice: 410.10,
        image: 'https://bestofwines.com/wine-images/26735_big.webp',
    },
    {
        _creator: '619ac04f96bfc93671b2be9f',
        name: 'Abstract',
        description: 'Deep garnet-purple colored, the 2019 Proprietary Red Abstract leaps from the glass with a pretty perfume of chocolate-covered cherries, stewed plums and kirsch with hints of Chinese five spice, menthol and Ceylon tea plus a waft of wild sage. Medium to full-bodied, the palate has lovely purity with juicy black and red berry flavors and a soft texture, finishing with a minty lift.',
        type: 'red',
        brand: 'Orin Swift',
        grape: ['coupage'],
        country: 'united states',
        region: 'napa valley',
        year: 2019,
        volume: 1.500,
        basePrice: 102.80,
        image: 'https://bestofwines.com/wine-images/26692_big.webp',
    },
    {
        _creator: '619ac04f96bfc93671b2be9f',
        name: 'Corton Charlemagne',
        description: 'Nutty, oily, and a little creamy on the nose. All about non-fruit. Density and texture on the palate. Very savoury with notes similar to Hermitage – nuts and straw – while retaining freshness and crunch.',
        type: 'white',
        brand: 'AF Gros',
        grape: ['chardonnay'],
        country: 'france',
        region: 'burgundy',
        year: 2018,
        volume: 0.750,
        basePrice: 235.95,
        discountPercentage: 10,
        image: 'https://bestofwines.com/wine-images/21221_big.webp',
    },
    {
        _creator: '619ac04f96bfc93671b2be9f',
        name: 'Brut Rose',
        description: 'Very pale salmon-pink in color, the 2005 Richard G. Peterson Brut Rosé has a gorgeous nose of fresh raspberries, wild strawberries, Red Delicious apples and white blossoms with underlying nuances of baking bread, shaved almonds and lanolin. The palate is fresh and lively with very fine bubbles, vibrant red berries and a nice mineral tinge, finishing long and toasty.',
        type: 'sparkling',
        brand: 'Amuse Bouche Richard G, Peterson',
        grape: ['coupage'],
        country: 'united states',
        region: 'napa valley',
        year: 2005,
        volume: 0.750,
        basePrice: 189.91,
        image: 'https://bestofwines.com/wine-images/16958_big.webp',
    },
];

module.exports = data;