const data = [
    // {
    //     _creator: '619ac04f96bfc93671b2be9f',
    //     name: 'Bonnes Mares',
    //     description: 'Deep and elegantly muscular, the 2019 Bonnes-Mares Grand Cru (Domaine Louis Jadot) is a layered, fleshy but tightly wound wine evocative or orange rind, rose petals, sweet berry fruit and raw cocoa. Full-bodied and concentrated, with a long, mineral finish, it will reward bottle age.',
    //     type: 'red',
    //     brand: 'Jadot',
    //     grape: ['pinot noir'],
    //     country: 'france',
    //     region: 'burgundy',
    //     year: 2019,
    //     volume: 0.750,
    //     basePrice: 410.10,
    //     image: 'https://bestofwines.com/wine-images/26735_big.webp',
    // },
    // {
    //     _creator: '619ac04f96bfc93671b2be9f',
    //     name: 'Abstract',
    //     description: 'Deep garnet-purple colored, the 2019 Proprietary Red Abstract leaps from the glass with a pretty perfume of chocolate-covered cherries, stewed plums and kirsch with hints of Chinese five spice, menthol and Ceylon tea plus a waft of wild sage. Medium to full-bodied, the palate has lovely purity with juicy black and red berry flavors and a soft texture, finishing with a minty lift.',
    //     type: 'red',
    //     brand: 'Orin Swift',
    //     grape: ['coupage'],
    //     country: 'united states',
    //     region: 'napa valley',
    //     year: 2019,
    //     volume: 1.500,
    //     basePrice: 102.80,
    //     image: 'https://bestofwines.com/wine-images/26692_big.webp',
    // },
    // {
    //     _creator: '619ac04f96bfc93671b2be9f',
    //     name: 'Corton Charlemagne',
    //     description: 'Nutty, oily, and a little creamy on the nose. All about non-fruit. Density and texture on the palate. Very savoury with notes similar to Hermitage – nuts and straw – while retaining freshness and crunch.',
    //     type: 'white',
    //     brand: 'AF Gros',
    //     grape: ['chardonnay'],
    //     country: 'france',
    //     region: 'burgundy',
    //     year: 2018,
    //     volume: 0.750,
    //     basePrice: 235.95,
    //     discountPercentage: 10,
    //     image: 'https://bestofwines.com/wine-images/21221_big.webp',
    // },
    // {
    //     _creator: '619ac04f96bfc93671b2be9f',
    //     name: 'Brut Rose',
    //     description: 'Very pale salmon-pink in color, the 2005 Richard G. Peterson Brut Rosé has a gorgeous nose of fresh raspberries, wild strawberries, Red Delicious apples and white blossoms with underlying nuances of baking bread, shaved almonds and lanolin. The palate is fresh and lively with very fine bubbles, vibrant red berries and a nice mineral tinge, finishing long and toasty.',
    //     type: 'sparkling',
    //     brand: 'Amuse Bouche Richard G, Peterson',
    //     grape: ['coupage'],
    //     country: 'united states',
    //     region: 'napa valley',
    //     year: 2005,
    //     volume: 0.750,
    //     basePrice: 189.91,
    //     image: 'https://bestofwines.com/wine-images/16958_big.webp',
    // },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Treinta Y Dos',
        description: 'Extremely perfumed with rose-petal, violet, rose-stem and sweet-strawberry aromas that follow through to a full-bodied palate with tight, juicy tannins that are strong and intense. A very structured, young, top pinot from here. Needs three to four years to soften.',
        type: 'white',
        brand: 'Chacra',
        grape: ['pinot noir'],
        country: 'argentina',
        region: 'patagonia',
        year: 2019,
        volume: 0.750,
        basePrice: 96.74,
        image: 'https://bestofwines.com/wine-images/27136_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Sur Saluces',
        description: 'Pale gold colored, the 1998 d\'Yquem features a flamboyant, rock-star nose of allspice, candied ginger, honeycomb and crème brûlée with a core of preserved lemons, mandarin peel and musk perfume plus a waft of potpourri. Beautifully balanced in the mouth, with seamless freshness lifting the decadent sweetness (134.4 grams per liter of residual sugar), it culminates with fantastically persistent layers of exotic spices.',
        type: 'dessert',
        brand: 'Chateau D\'Yquem',
        grape: ['coupage'],
        country: 'france',
        region: 'bordeaux',
        year: 1998,
        volume: 0.750,
        basePrice: 325.49,
        image: 'https://bestofwines.com/wine-images/15375_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Sur Saluces',
        description: 'The 2018 d\'Yquem is all lime cordial, grapefruit oil and mandarin peel to begin. With a little coaxing, the fireworks really begin, letting off a whole array of honeysuckle, candied ginger, dried pineapple, lemon pastilles, chalk dust and sea spray scents, followed by a savory undercurrent of shaved almonds, allspice and baking bread. The palate is an exercise in polish and poise, featuring the most gorgeously creamy texture and bright, sparkling freshness, framing all the densely laden tropical and citrus fruit layers, finishing with a powerful BANG of profound floral and spice perfume. It is wonderfully sweet, yes, but that—paradoxically for a "sweet wine"—is almost beside the point.',
        type: 'dessert',
        brand: 'Chateau D\'Yquem',
        grape: ['coupage'],
        country: 'france',
        region: 'bordeaux',
        year: 2018,
        volume: 1.5,
        basePrice: 724.79,
        image: 'https://bestofwines.com/wine-images/23247-2_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Sur Saluces',
        description: 'Pale gold colored, the 1998 d\'Yquem features a flamboyant, rock-star nose of allspice, candied ginger, honeycomb and crème brûlée with a core of preserved lemons, mandarin peel and musk perfume plus a waft of potpourri. Beautifully balanced in the mouth, with seamless freshness lifting the decadent sweetness (134.4 grams per liter of residual sugar), it culminates with fantastically persistent layers of exotic spices.',
        type: 'dessert',
        brand: 'Chateau D\'Yquem',
        grape: ['coupage'],
        country: 'france',
        region: 'bordeaux',
        year: 1998,
        volume: 0.750,
        basePrice: 325.49,
        image: 'https://bestofwines.com/wine-images/15375_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Amber',
        description: 'Rene Gabriel rates this wine 17/20 points.',
        type: 'dessert',
        brand: 'Chateau Raymond Lafon',
        grape: ['coupage'],
        country: 'france',
        region: 'bordeaux',
        year: 1997,
        volume: 0.750,
        basePrice: 56.81,
        image: 'https://bestofwines.com/wine-images/24969_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Whispering Angel',
        description: 'A crowd-pleasing rosé, with white strawberry, mineral and rose petal flavors that are graceful and pure. Details of mineral, spice and melon fine-tune the supple finish.',
        type: 'rose',
        brand: 'Chateau d\'Esclans',
        grape: ['coupage'],
        country: 'france',
        region: 'provence',
        year: 2020,
        volume: 0.750,
        basePrice: 21.95,
        image: 'https://bestofwines.com/wine-images/23558-2_big.jpg',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Chateau Romassan',
        description: 'A blend of 60% Mourvèdre, 25% Cinsault and 15% Grenache, the 2019 Bandol Rose Chateau Romassan boasts flowing, elegant aromas of crushed stone, wild strawberries, raspberries, melon and ripe citrus. It\'s medium to full-bodied, delivering plenty of flavor intensity on the silky palate, then gradually fading on the long finish.',
        type: 'rose',
        brand: 'Domaines Ott',
        grape: ['coupage'],
        country: 'france',
        region: 'provence',
        year: 2019,
        volume: 0.750,
        basePrice: 36.24,
        image: 'https://bestofwines.com/wine-images/21510_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Vina Tondonia Gran Reserva Rosado',
        description: '2011 is a warmer and riper year in Rioja than 2010, which was a superb vintage, and the 2011 Viña Tondonia Rosado Gran Reserva suffers when tasted next to the 2010. It has candied fruit and a much riper profile but with the classical old oak and mushroom aromas of Tondonia. The color is less bright than the 2010, and there are already some brick-going-to-brown tones. There is some lightness in the palate with moderate acidity and refreshing notes of watermelon and rose petals. 12,000 bottles were filled in April 2017.',
        type: 'rose',
        brand: 'Lopez de Heredia',
        grape: ['coupage'],
        country: 'spain',
        region: 'rioja',
        year: 2011,
        volume: 0.750,
        basePrice: 71.39,
        image: 'https://bestofwines.com/wine-images/26924_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Sof',
        description: 'JS Aromas of blackcurrants and hints of cassis bush. Some basil, too. Full body, velvety tannins and a flavorful finish. Dense and delicious. Better in 2019 but a pretty polish to this',
        type: 'rose',
        brand: 'Tenuta di Biserno',
        grape: ['cabernet', 'merlot', 'petit verdot'],
        country: 'italy',
        region: 'tuscany',
        year: 2020,
        volume: 0.750,
        basePrice: 30.19,
        image: 'https://bestofwines.com/wine-images/25209_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Etoile',
        description: 'Étoile is the apotheosis of the Domaines Ott* terroirs and the most beautiful expression of a prestige rosé from Provence. The fruit is explosive, honest, bright and true to the Ott signature style yet it also takes its aromatic depth further with its exquisite body and mouthfeel. The subtle signs of ageing integrate smoothly into the intensity of the fruit, with its fresh, crunchy notes, subtle salinity and perfect balance. Richness and power merge and take on a new dimension, united in a newfound intensity, freshness and seductive opulence.',
        type: 'rose',
        brand: 'Domaines Ott',
        grape: ['coupage'],
        country: 'france',
        region: 'provence',
        year: 2019,
        volume: 0.750,
        basePrice: 111.26,
        image: 'https://bestofwines.com/wine-images/21508_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Beaune 1er Cru les Boucherottes',
        description: 'Ripe and rich on the nose. Dark cherries and sweet plums with a little baked vanilla. Great intensity on the palate. Creamy red fruit. Surprising richness but the tannins come in slightly angular and firm. Chalky finish, where the fruit lingers longer than expected.',
        type: 'red',
        brand: 'AF Gros',
        grape: ['pinot noir'],
        country: 'france',
        region: 'burgundy',
        year: 2018,
        volume: 0.750,
        basePrice: 61.75,
        image: 'https://bestofwines.com/wine-images/21227_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Echezeaux',
        description: 'The 2015 Echézeaux Grand Cru was buttoned down when I tasted it, the 100% new oak keeping a lid on the red berry fruit behind this wall. The palate is grippy on the entry with chunky red berry fruit (cranberry, wild strawberry and pomegranate) mixed with white pepper and sage notes towards the stocky finish. Like other 2015s from the domaine, I would like more terroir expression, more personality to be expressed.',
        type: 'red',
        brand: 'AF Gros',
        grape: ['pinot noir'],
        country: 'france',
        region: 'burgundy',
        year: 2015,
        volume: 0.750,
        basePrice: 373.89,
        image: 'https://bestofwines.com/wine-images/14176_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Barolo Bussia',
        description: 'Always a reliable introductory bottling, the 2001 Barolo Bussia, a lively ruby, presents an aromatic and floral nose, with notes of spices, mint and minerals. It displays clean, focused flavors of ripe red fruit on a soft, medium-bodied frame, finishing with good length and freshness. This classy and refined Barolo is made from a blend of parcels in the Bussia zone that are less well-exposed, and therefore not considered ‘cru’ level quality. Anticipated maturity: 2008-2016.',
        type: 'red',
        brand: 'Aldo Conterno',
        grape: ['nebbiolo'],
        country: 'italy',
        region: 'piemont',
        year: 2001,
        volume: 0.750,
        basePrice: 130.68,
        image: 'https://bestofwines.com/wine-images/13569-2_big.jpg',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Alion',
        description: 'The 2017 Alión, the only wine produced here, comes from a challenging year marked by spring frost and a warm and dry end of the season, so they reduced the amount of new oak by 8%. It fermented with indigenous yeasts, and 10% of the volume aged in concrete, completely unoaked. The change in the oak regimen helped with the style of the vintage, which was marked by the frost that hit part of the Alión vineyards. Furthermore, the end of the season was warm and dry, and they had to work to control ripeness and power and perhaps the possibility of more aggressive tannins. It\'s a classical Alión, with some developed aromas, juicy and round but not heavy, with just a tad of earthy rusticity. With time, it develops more balsamic notes and hints of licorice',
        type: 'red',
        brand: 'Alion Bodegas',
        grape: ['tempranillo'],
        country: 'spain',
        region: 'ribera del duero',
        year: 2017,
        volume: 0.750,
        basePrice: 82.28,
        image: 'https://bestofwines.com/wine-images/26601_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Palafreno',
        description: 'Black cherry and banana peel aromas segue to dark, brooding blackberry, plum, iron and underbrush flavors in this austere, powerful red. Dusty tannins leave a strong grip as this plays out on the long finish.',
        type: 'red',
        brand: 'Agricole Querciabella',
        grape: ['merlot'],
        country: 'italy',
        region: 'tuscany',
        year: 2016,
        volume: 0.750,
        basePrice: 142.72,
        image: 'https://bestofwines.com/wine-images/25876_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Los Posadas',
        description: 'Deep garnet-purple colored, the 2014 Las Posadas Proprietary Red opens with tons of wild blueberry, mulberries and cassis notes over garrigue, sage, baking spices and dusty soil plus touches of Black Forest cake and cedar. The rich, full-bodied palate is rugged, muscular, lively and concentrated with firm, grainy tannins, finishing very long and earthy.',
        type: 'red',
        brand: 'Abreu',
        grape: ['coupage'],
        country: 'united states',
        region: 'napa valley',
        year: 2014,
        volume: 0.750,
        basePrice: 640.09,
        image: 'https://bestofwines.com/wine-images/18080_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Rive Droite',
        description: 'Jeb Dunnuck: The Merlot-dominated 2017 Merlot Rive Droite Paradise Hills Vineyard (there\'s 4% Cabernet Franc in the blend) is also straight-up brilliant, showing tons of ripe black cherry, chocolate, coffee bean, and truffly herb aromas and flavors. Full-bodied and powerful, it has the same elegant tannin structure found in the Proprietary Red, nicely integrated acidity, terrific purity, and a great finish. It\'s not for those looking for massive richness and decadence, but it has a purity, elegance, and minerality that makes it a joy to drink.',
        type: 'red',
        brand: 'Blankiet',
        grape: ['merlot'],
        country: 'united states',
        region: 'napa valley',
        year: 2017,
        volume: 0.750,
        basePrice: 221.43,
        image: 'https://bestofwines.com/wine-images/23257-2_big.jpg',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Gold Brut',
        description: 'Tasted from magnum, the NV Brut (Gold) opens with lovely matured brioche, toast and ripe fruit flavors. Fresh, pure and elegant on the palate, with beautifully matured flavors and an elegant creaminess I don\'t find in the other cuvées, the "Gold" is a blend of 40% Pinot noir, 40% Chardonnay and 20% Pinot meunier as well as the vintages of 2009, 2010 and 2012. The wine reveals good grip and mineral tension and drinks well as an aperitif or with seafood and fish.',
        type: 'sparkling',
        brand: 'Armand de Brignac',
        grape: ['pinot noir', 'pinot meunier', 'chardonnay'],
        country: 'france',
        region: 'champagne',
        year: 2020,
        volume: 0.750,
        basePrice: 277.09,
        image: 'https://bestofwines.com/wine-images/3452_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Brut Cuvee Nicolas Francois',
        description: 'Disgorged with six grams per liter dosage, the 2007 Brut Cuvée Nicolas François is showing very nicely, offering up aromas of fresh bread, citrus oil, crisp yellow orchard fruit, white flowers, verbena, macadamia nut and hints of biscuity complexity to come. Full-bodied, chiseled but fleshy, its vinous core of fruit cloaks the vintage\'s brisk acids to achieve real plenitude in a year that\'s sometimes rather tautly austere. Long and penetrating and complemented by a pretty pinpoint mousse, this is a real success.',
        type: 'sparkling',
        brand: 'Billecart Salmon',
        grape: ['pinot noir', 'pinot meunier', 'chardonnay'],
        country: 'france',
        region: 'champagne',
        year: 2007,
        volume: 0.750,
        basePrice: 156.09,
        image: 'https://bestofwines.com/wine-images/26050_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Fut de Chene MV16 Grand Cru',
        description: 'Elegant overall, with a refined, creamy texture and beautiful integration. This rich Champagne displays power and focus, with expansive flavors of baked currant, plum, bread dough, crystallized honey, ground clove, grated coconut and ginger on the long-lasting finish.',
        type: 'sparkling',
        brand: 'Henri Giraud',
        grape: ['pinot noir', 'chardonnay'],
        country: 'france',
        region: 'champagne',
        year: 2020,
        volume: 0.750,
        basePrice: 159.72,
        image: 'https://bestofwines.com/wine-images/24375_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Champagne Belle Epoque',
        description: 'A very complex and toasty nose with nicely cut, autolytic, reductive kick that adds flinty notes to the lemons and pink grapefruit, as well as fresh, lightly spiced pastry. The palate has a super fluid and attractively fresh feel with a bold, sweetly fruited core that delivers a long, succulent and elegant finish. This is in form!',
        type: 'sparkling',
        brand: 'Perrier Jouet',
        grape: ['pinot noir', 'pinot meunier', 'chardonnay'],
        country: 'france',
        region: 'champagne',
        year: 2012,
        volume: 0.750,
        basePrice: 172.97,
        image: 'https://bestofwines.com/wine-images/20123_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Cumieres Premier Cru Brut Nature',
        description: 'A very complex and toasty nose with nicely cut, autolytic, reductive kick that adds flinty notes to the lemons and pink grapefruit, as well as fresh, lightly spiced pastry. The palate has a super fluid and attractively fresh feel with a bold, sweetly fruited core that delivers a long, succulent and elegant finish. This is in form!',
        type: 'sparkling',
        brand: 'Georges Laval',
        grape: ['pinot noir', 'pinot meunier', 'chardonnay'],
        country: 'france',
        region: 'champagne',
        year: 2013,
        volume: 1.5,
        basePrice: 258.94,
        image: 'https://bestofwines.com/wine-images/25621_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Batar',
        description: 'Cooked apple, honey and light vanilla with some stone and praline undertones. Full-bodied with layers of fruit and a flavorful finish. White peaches,too. Fantastic white. From biodynamically and organically grown chardonnay and pinot bianco.',
        type: 'white',
        brand: 'Agricole Querciabella',
        grape: ['chardonnay', 'pinot blanc'],
        country: 'italy',
        region: 'tuscany',
        year: 2018,
        volume: 0.750,
        basePrice: 83.49,
        image: 'https://bestofwines.com/wine-images/25872_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Pinot Gris Grains Nobles',
        description: 'A pungent dessert white, offering hard lemon candy, almond and orange marmalade flavors. Intense and muscular, yet not that sweet, with a touch of alcohol showing on the finish.',
        type: 'white',
        brand: 'Trimbach',
        grape: ['coupage'],
        country: 'france',
        region: 'alsace',
        year: 2000,
        volume: 0.750,
        basePrice: 84.64,
        image: 'https://bestofwines.com/wine-images/14212_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Chardonnay Larry Hyde and Sons Vineyard Carneros',
        description: 'Aubert noted that this is his coolest site and usually the last to be harvested. Located near the Hyde Estate winery, by virtue of chilly afternoon breezes, it is indeed among the coolest sites on the Napa side of the Los Carneros AVA. This section is planted to Corton-Charlemagne clone on St. George rootstock. A barrel sample, it is being aged in 50% new French oak barrels.',
        type: 'white',
        brand: 'Aubert',
        grape: ['chardonnay'],
        country: 'united states',
        region: 'sonoma',
        year: 2019,
        volume: 0.750,
        basePrice: 192.39,
        image: 'https://bestofwines.com/wine-images/25081_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Maya Proprietary Red Wine',
        description: 'The very deep garnet-purple colored 2018 Maya is shy and restrained to begin. With swirling, it begins to reveal beguiling notes of fragrant earth, lavender, garrigue and Sichuan pepper, giving way to a core of wild blueberries, boysenberries, black raspberries and black currants plus a hint of iron ore. The palate is full-bodied, revealing itself in slow-releasing layers of black and blue fruits with exhilarating earth and mineral sparks, framed by firm, beautifully ripe tannins and bold freshness, finishing on a persistent ferrous note. As cerebral as it is downright hedonic, this Maya is simply jaw-dropping.',
        type: 'red',
        brand: 'Dalla Valle',
        grape: ['coupage'],
        country: 'united states',
        region: 'napa valley',
        year: 2018,
        volume: 0.750,
        basePrice: 567.49,
        image: 'https://bestofwines.com/wine-images/27038_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Cervaro della Sala',
        description: 'The Castello della Sala 2019 Cervaro della Sala relies on a time-honored formula in which the Grechetto grape adds vertical intensity and freshness and Chardonnay gives structure and sophistication. Indeed, Grechetto (with late-harvest clones) never goes above 10% of the blend, and no malolactic fermentation is performed on that variety in order to maintain its tonic and fresh personality. This stunning edition shows orchard fruit, honey and flinty notes. The Chardonnay ferments in neutral barrique from September to February, and fine-grained wood is prioritized to render a reductive winemaking technique to further preserve aromatic intensity. This mid-weight and age-worthy white is redolent of Golden Delicious apple, acacia flower and tropical fruit.',
        type: 'white',
        brand: 'Antinori',
        grape: ['coupage'],
        country: 'italy',
        region: 'umbrie',
        year: 2019,
        volume: 0.750,
        basePrice: 66.49,
        image: 'https://bestofwines.com/wine-images/25144_big.webp',
    },
    {
        _creator: '61afb66abbda6fc832d30e98',
        name: 'Les Argales',
        description: 'Blend of Savignin and Chardonnay. Wine is Orange tainted due to maceration technique.',
        type: 'white',
        brand: 'Nicolas Jacob',
        grape: ['chardonnay'],
        country: 'france',
        region: 'jura',
        year: 2018,
        volume: 0.750,
        basePrice: 66.49,
        image: 'https://bestofwines.com/wine-images/23699_big.webp',
    },
];
'';
module.exports = data;